CUDA_VISIBLE_DEVICES=1 python trainer.py \
    --data_dir ./data \
    --train_path ./data/mwoz21/train_ext_1pct_seed47_set0.json \
    --dev_path ./data/mwoz21/dev_ext.json \
    --test_path ./data/mwoz21/test_ext.json \
    --model_name_or_path t5-base \
    --output_dir ./out \
    --strategy ddp \
    --batch_size_per_gpu 64 \
    --num_workers 8 \
    --lr 5e-4 \
    --accumulate_grad_batches 4 \
    --weight_decay 0.01 \
    --exp_no exp17t \
    --project ds2-losey-t5 \
    --gradient_clip_val 1.0 \
    --warmup_steps -1 \
    --seed 42 \
    --max_steps -1 \
    --gpus 1 \
    --max_epochs 10 \
    --do_test_only \
    --num_beams 2 \
    --patience 3 \
    --data_ver 21 \
    --num_slots 30 \
    --enc_max_seq_len 1024 \
    --ckpt_path ./out/exp17/exp17/checkpoints/epoch=04-val_loss=0.03.ckpt